# Tokens from the Facebook page web hooks
# ACCESS_TOKEN = "YOUR-ACCESS-TOKEN"
# VERIFY_TOKEN = "YOUR-VERIFY-TOKEN"

ACCESS_TOKEN = "EAAc63lNnaXwBAH59r33GfPPbzudUCgzgJWYe7up6o1DqwWHOokDxSQ5FBLtpkvuwquTcZAF2U1uNqvJHvxZCZCTWxZBArIMGtDlnSzZClmOYCQ5ZAUUrU1Tm3w514DgKACKWXhHdf2g2nT038uBZCPZC9ZA8jS15cgn1kvL6CiQjboQZDZD"
VERIFY_TOKEN = "pisang-bananana"